#ifndef _MENUS_MACROS_H
#define _MENUS_MACROS_H

// CORNER_MAIN_MENU 0, 0
// CORNER_LEADERBOARD 0, 0

#define CURSOR_INICIAL_X 140
#define CURSOR_INICIAL_Y 350

#define CURSOR_WIDTH 34
#define CURSOR_HEIGHT 42

#define MENUS_BACKGROUND_COLOR 0x000533
#define MENUS_BORDERS 0xbaaeae

#define TITLE_TO_X 192
#define TITLE_TO_Y 59
#define TITLE_WIDTH 415
#define TITLE_HEIGHT 205

#define BUTTONS_BUTTON_WIDTH 234
#define BUTTONS_BUTTON_HEIGHT 61

#define MAIN_SOLO_BUTTON_TO_X 132
#define MAIN_SOLO_BUTTON_TO_Y 334
#define MAIN_LEADERBOARD_BUTTON_TO_X 132
#define MAIN_LEADERBOARD_BUTTON_TO_Y 445
#define MAIN_1V1_BUTTON_TO_X 445
#define MAIN_1V1_BUTTON_TO_Y 334
#define MAIN_EXIT_BUTTON_TO_X 445
#define MAIN_EXIT_BUTTON_TO_Y 445

#define LEADER_EXIT_BUTTON_TO_X 540
#define LEADER_EXIT_BUTTON_TO_Y 520
#define LEADER_BACK_BUTTON_TO_X 25
#define LEADER_BACK_BUTTON_TO_Y 520
#define TABLE_TO_X 70
#define TABLE_TO_Y 310

#define MENU_PAUSE_CORNER_X 80
#define MENU_PAUSE_CORNER_Y 120
#define MENU_PAUSE_WIDTH 640
#define MENU_PAUSE_HEIGHT 410

#define PAUSE_TITLE_TO_X 180
#define PAUSE_TITLE_TO_Y 33
#define PAUSE_TITLE_WIDTH 280
#define PAUSE_TITLE_HEIGHT 95

#define PAUSE_BUTTONS_TO_X 203
#define PAUSE_CONTINUE_BUTTON_TO_Y 152
#define PAUSE_RESET_BUTTON_TO_Y 233
#define PAUSE_EXIT_BUTTON_TO_Y 314
#define PAUSE_BETWEEN_BUTTONS 10

#define MENU_BORDER_SIZE 5


#endif
